// <auto-generated />
using System;
using DigitalTwin.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalTwin.Api.Persistence.Migrations
{
    [DbContext(typeof(PlayerEventDbContext))]
    [Migration("20260922073937_AffectNonPrononce")]
    partial class AffectNonPrononce
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalTwin.Api.Persistence.MemoryRow", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("TargetKind")
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.Property<string>("TargetId")
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "TargetKind", "TargetId");

                    b.HasIndex("UserId");

                    b.ToTable("memories", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Api.Persistence.PlayDeclarationRow", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkId")
                        .HasColumnType("text")
                        .HasColumnName("work_id");

                    b.Property<string>("PlatformId")
                        .HasColumnType("text")
                        .HasColumnName("platform_id");

                    b.Property<string>("Affect")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("affect");

                    b.Property<bool>("NeverPlayed")
                        .HasColumnType("boolean")
                        .HasColumnName("never_played");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provenance");

                    b.HasKey("UserId", "WorkId", "PlatformId");

                    b.HasIndex("UserId");

                    b.ToTable("play_declarations", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Api.Persistence.PlayerEventRow", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BatchId")
                        .HasColumnType("text")
                        .HasColumnName("batch_id");

                    b.Property<int?>("OccurredAge")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_age");

                    b.Property<DateOnly?>("OccurredDate")
                        .HasColumnType("date")
                        .HasColumnName("occurred_date");

                    b.Property<int?>("OccurredEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_end_year");

                    b.Property<string>("OccurredKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occurred_kind");

                    b.Property<int?>("OccurredMargin")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_margin");

                    b.Property<int?>("OccurredMonth")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_month");

                    b.Property<int?>("OccurredYear")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_year");

                    b.Property<string>("PlatformId")
                        .HasColumnType("text")
                        .HasColumnName("platform_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SupersededByEventId")
                        .HasColumnType("text")
                        .HasColumnName("superseded_by_event_id");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "BatchId");

                    b.HasIndex("UserId", "TargetId");

                    b.ToTable("player_events", (string)null);
                });

            modelBuilder.Entity("DigitalTwin.Api.Persistence.UnresolvedClaimRow", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_title");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform_id");

                    b.Property<string>("ResolvedWorkId")
                        .HasColumnType("text")
                        .HasColumnName("resolved_work_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "NormalizedTitle", "PlatformId")
                        .IsUnique();

                    b.ToTable("unresolved_claims", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
