// <auto-generated />
using System;
using DigitalTwin.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalTwin.Api.Persistence.Migrations
{
    [DbContext(typeof(PlayerEventDbContext))]
    partial class PlayerEventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalTwin.Api.Persistence.PlayerEventRow", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("OccurredAge")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_age");

                    b.Property<DateOnly?>("OccurredDate")
                        .HasColumnType("date")
                        .HasColumnName("occurred_date");

                    b.Property<int?>("OccurredEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_end_year");

                    b.Property<string>("OccurredKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occurred_kind");

                    b.Property<int?>("OccurredMargin")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_margin");

                    b.Property<int?>("OccurredMonth")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_month");

                    b.Property<int?>("OccurredYear")
                        .HasColumnType("integer")
                        .HasColumnName("occurred_year");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SupersededByEventId")
                        .HasColumnType("text")
                        .HasColumnName("superseded_by_event_id");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TargetId");

                    b.ToTable("player_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
